### ISSUE TITLE
`assure` command fails with "AttributeError: 'list' object has no attribute 'items'"

### ISSUE THREAD

**Issue by Jongmassey** [opensafely-core/ehrql#2079]
@milanwiedemann reported a problem with `assure` in this [Slack thread](https://bennettoxford.slack.com/archives/C33TWNQ1J/p1722509825623859)

I can replicate this problem. Using the example `dataset_definition.py` and `test_dataset_definition.py` from [How to test your dataset definition](https://docs.opensafely.org/ehrql/how-to/test-dataset-definition/) in the ehrql docs, I get the following error output from the `assure` command

```sh

$ opensafely exec ehrql:v1 assure analysis/test_dataset_definition.py
Traceback (most recent call last):
  File "/opt/venv/bin/ehrql", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/app/ehrql/__main__.py", line 75, in entrypoint
    return main(sys.argv[1:], environ=os.environ)  # pragma: no cover
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/ehrql/__main__.py", line 102, in main
    function(**kwargs)
  File "/app/ehrql/main.py", line 343, in assure
    results = assurance.validate(variable_definitions, test_data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/ehrql/assurance.py", line 36, in validate
    constraints_error = validate_constraints(records, table)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/ehrql/assurance.py", line 72, in validate_constraints
    for column, value in record.items():
                         ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'items'

```

when starting from a fresh repo based on the research-template.

**Comment by evansd** [comment]
Following further discussion in [another thread](https://bennettoxford.slack.com/archives/C069YDR4NCA/p1722519433993609) the issue appears to be an invalid example rather than a bug in ehrQL.

In the example test script, the  `patients` data for the first patient is defined correctly as a dict:
```
test_data = {
    # Expected in population with matching medication
    1: {
        "patients": {"date_of_birth": date(1950, 1, 1)},
        "medications": [
            {
                # First matching medication
                "date": date(2010, 1, 1),
                "dmd_code": "39113311000001107",
            },
...
```

But the second and third patients are defined as a list of dicts:
```
2: {
        "patients": [{"date_of_birth": date(1950, 1, 1)}],
        "medications": [],
   ...
```
Which is causing the error, because the script expects a one-row-per-patient table to be defined as a dict.

We should therefore:
 * Fix the example.
 * Consider whether it might be reasonable to accept a list containing a single dict where we expect only one dict. The users intention seems clear and they have supplied the necessary data, just not in quite the right form.
 * Consider adding stricter validation here so supplying the wrong type of thing results in a clear error message rather than e.g. an attribute error. These are user-supplied values and so this interfaces forms part of our UI which makes it worth investing in helpful errors here.

**Comment by mikerkelly** [comment]
Removing tech-support label as I don't think we need actively follow this up or get back further to the reporter. We have captured all information needed to resolve the issue and the reporter isn't expecting further responses.
