### ISSUE TITLE
Inconsistent capitalisation of "the" causing problems with example data

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/ehrql#2106]
The [example data](https://github.com/opensafely-core/ehrql/blob/main/ehrql/example-data/practice_registrations.csv) reference "Yorkshire and the Humber", while our [table validation](https://github.com/opensafely-core/ehrql/blob/ad304d3dd213b2cb468c19829c1bc72b4e6e183a/ehrql/tables/tpp.py#L1333) checks for "Yorkshire and The Humber".

This causes problems in the sandbox:

```
(.venv) inglesp@malbogies:~/work/ebmdatalab/ehrql$ python -m ehrql sandbox ehrql/example-data
Python 3.11.10 (main, Sep  7 2024, 18:35:41) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from ehrql.tables.tpp import practice_registrations
>>> practice_registrations
Traceback (most recent call last):
  File "/home/inglesp/work/ebmdatalab/ehrql/ehrql/file_formats/csv.py", line 145, in parser
    return convertor(value)
           ^^^^^^^^^^^^^^^^
  File "/home/inglesp/work/ebmdatalab/ehrql/ehrql/file_formats/csv.py", line 168, in wrapper
    raise ValueError(f"{value!r} not in valid categories: {category_str}")
ValueError: 'Yorkshire and the Humber' not in valid categories: 'North East', 'North West', 'Yorkshire and The Humber', 'East Midlands', 'West Midlands', 'East', 'London', 'South East', 'South West'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inglesp/work/ebmdatalab/ehrql/ehrql/file_formats/csv.py", line 83, in __iter__
    yield row_parser(row)
          ^^^^^^^^^^^^^^^
  File "/home/inglesp/work/ebmdatalab/ehrql/ehrql/file_formats/csv.py", line 110, in row_parser
    return tuple(parser(row) for parser in parsers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inglesp/work/ebmdatalab/ehrql/ehrql/file_formats/csv.py", line 110, in <genexpr>
    return tuple(parser(row) for parser in parsers)
                 ^^^^^^^^^^^
  File "/home/inglesp/work/ebmdatalab/ehrql/ehrql/file_formats/csv.py", line 147, in parser
    raise ValueError(f"column {name!r}: {e}")
ValueError: column 'practice_nuts1_region_name': 'Yorkshire and the Humber' not in valid categories: 'North East', 'North West', 'Yorkshire and The Humber', 'East Midlands', 'West Midlands', 'East', 'London', 'South East', 'South West'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
ehrql.file_formats.base.FileValidationError: row 8: column 'practice_nuts1_region_name': 'Yorkshire and the Humber' not in valid categories: 'North East', 'North West', 'Yorkshire and The Humber', 'East Midlands', 'West Midlands', 'East', 'London', 'South East', 'South West'
```

**Comment by inglesp** [comment]
We should:

- [ ] Double check that "The" appears in the data
- [ ] Fix the example data (or the validation if that's incorrect)
- [ ] Add a test that all example data can be loaded

**Comment by evansd** [comment]
This feels fairly high priority, given that we encourage use of the sandbox for new learners.
