### ISSUE TITLE
Test parallelisation config breaks pytest `--pdb` option

### ISSUE THREAD

**Issue by evansd** [opensafely-core/ehrql#941]
The pytest `--pdb` option drops you into a debugger on hitting an error. However when I try to use it I get the error:
```
ERROR: --pdb is incompatible with distributing tests; try using -n0 or -nauto.
```

Removing the `--dist=loadgroup` option from `tool.pytest.ini_options` in `pyproject.toml` fixes the issue for me:
https://github.com/opensafely-core/databuilder/blob/a635020371cd2cae4e2c2ca7ae0c7e7c94215fd3/pyproject.toml#L106

**Comment by inglesp** [comment]
If you add `-n0` to pyproject.yaml, does it work?  And can you then override this with `-n2` from the command line?

If this doesn't work, we should remove `--dist=loadgroup` from pyproject.yaml.

**Comment by evansd** [comment]
No, adding `-n0` to the arguments in `pyproject.toml` doesn't make any difference.

**Comment by StevenMaude** [comment]
@evansd: Maybe try `--dist no`?

https://github.com/pytest-dev/pytest-xdist/pull/851/files#diff-010e3d93f82f582736659012db9428424291c3d52d75626f97294f1a8bc3a9f7R205

I think this seems to give the correct behaviour for me:

```
$ just test-no-spark --pdb
…
$BIN/python -m pytest -k "not spark" --pdb
ERROR: --pdb is incompatible with distributing tests; try using -n0 or -nauto.

error: Recipe `test-no-spark` failed on line 153 with exit code 4
```

With deliberate test error to change the name of a table introduced:

```
$ just test-no-spark --dist no --pdb
$BIN/python -m pytest -k "not spark" --dist no --pdb
=============================================================================================== test session starts ===============================================================================================
…
tests/unit/backends/test_base.py F
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Traceback (most recent call last):
  File "/home/bennett/.local/src/github.com/opensafely-core/databuilder/tests/unit/backends/test_base.py", line 45, in test_backend_registers_tables
    assert set(TestBackend.tables) == {
AssertionError: assert {'events', 'p...egistrations'} == {'apatients',...egistrations'}
  Extra items in the left set:
  'patients'
  Extra items in the right set:
  'apatients'
  Use -v to get more diff
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB post_mortem (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /home/bennett/.local/src/github.com/opensafely-core/databuilder/tests/unit/backends/test_base.py(45)test_backend_registers_tables()
-> assert set(TestBackend.tables) == {
(Pdb) 
```

**Comment by StevenMaude** [comment]
@evansd: Maybe try `--dist no`?

https://github.com/pytest-dev/pytest-xdist/pull/851/files#diff-010e3d93f82f582736659012db9428424291c3d52d75626f97294f1a8bc3a9f7R205

I think this seems to give the correct behaviour for me, *while leaving `pyproject.toml` unchanged*:

```
$ just test-no-spark --pdb
…
$BIN/python -m pytest -k "not spark" --pdb
ERROR: --pdb is incompatible with distributing tests; try using -n0 or -nauto.

error: Recipe `test-no-spark` failed on line 153 with exit code 4
```

With deliberate test error to change the name of a table introduced:

```
$ just test-no-spark --dist no --pdb
$BIN/python -m pytest -k "not spark" --dist no --pdb
=============================================================================================== test session starts ===============================================================================================
…
tests/unit/backends/test_base.py F
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Traceback (most recent call last):
  File "…/databuilder/tests/unit/backends/test_base.py", line 45, in test_backend_registers_tables
    assert set(TestBackend.tables) == {
AssertionError: assert {'events', 'p...egistrations'} == {'apatients',...egistrations'}
  Extra items in the left set:
  'patients'
  Extra items in the right set:
  'apatients'
  Use -v to get more diff
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB post_mortem (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> …/databuilder/tests/unit/backends/test_base.py(45)test_backend_registers_tables()
-> assert set(TestBackend.tables) == {
(Pdb) 
```

**Comment by evansd** [comment]
Oh nice! Thanks

**Comment by StevenMaude** [comment]
Is that sufficient to close this issue? :smiley:

**Comment by evansd** [comment]
Yeah, I think so. It's slightly annoying that you have to add this argument to make it work, but I'll remember I need it as soon as I see the error. And hopefully other people who encounter it will search the error message and find this issue.

**Comment by inglesp** [comment]
If nobody's running tests in parallel, we should remove the problematic config from pyproject.yaml.

**Comment by StevenMaude** [comment]
If we don't remove it, I've noted it in [`DEVELOPERS.md`](https://github.com/opensafely-core/databuilder/commit/dbbb8961cbd9a21b4bcab44a41bd0c9ff0f9f39a).
